blueprint:
  name: Arrive Notification
  description: Send a notification to a device when a person arrives in a specific zone.
  domain: automation
  input:
    person_entity:
      name: Person
      description: 
      selector:
        entity:
          filter:
            domain: person
    zone_entity:
      name: Zone      
      selector:
        entity:
          filter:
            domain: zone
    notify_device:
      name: Device to Notify
      description: Device needs to run offical Home Assistant app to receive notifications.
      selector:
        device:
          filter:
            integration: mobile_app    

trigger:
  platform: state
  entity_id: !input person_entity

variables:
  zone_entity: !input zone_entity
  # This is the state of the person when it's in this zone.
  zone_state: "{{ states[zone_entity].name }}"
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].name }}"

condition:
  condition: template
  # The first case handles arriving at the Home zone which has a special state 'home'.
  # The second case handles arriving at all other zones.
  value_template: >
    {{ (zone_entity == 'zone.home' and trigger.to_state.state == 'home' and trigger.from_state.state != 'home')
       or (trigger.to_state.state == zone_state and trigger.from_state.state != zone_state) }}

action:
  - alias: "Notify that a person has arrived at the zone"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: "{{ person_name }} has arrived at {{ zone_state }}"
